[workspace]
resolver = "2"
members = [
  "hayase-ext-pdk",
  "extensions/nyaa",
  "extensions/sukebei",
  "extensions/piratebay",
  "extensions/seadex",
  "extensions/animetosho",
  "extensions/animetosho_new",
  "extensions/subsplease",
  "extensions/tokyotosho",
  "extensions/yameii",
  "extensions/toonshub",
  "extensions/nekobt",
  "extensions/anisearch",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
extism-pdk = "1"
hayase-ext-pdk = { path = "hayase-ext-pdk" }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
